### PR TITLE
Synthesizing assignment

### PR DESCRIPTION
**Pull request by leoc1114**

### CODE REVIEW

**Comment by cheuschober** [comment]
@leoc1114,

This was opened against the wrong base fork. You shoudl open pull requests against is210-2015-spring-01

**Comment by cheuschober** [comment]
@leoc1114 You won't be able to get credit until you open your pull request against the correct branch.

**Comment by leoc1114** [comment]
I did this twice, one in this branch, another one in the correct branch. Please check the link I sent in.

**Comment by leoc1114** [comment]
Ok, thank you.

Sent from Samsung Mobile

-------- Original message --------

**Pull request closed without merging**
